version: '2'
services:
  build:
    build: .
    image: shimizukawa/freia
    volumes:
      - .:/doc
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    command: sphinx-build -M html /doc/source /doc/build -N -T -j 4
