# Makefile for Sphinx documentation
#

# You can set these variables from the command line.
PYTHON    = python

.PHONY: help clean html htmlgz dirhtml singlehtml pickle json htmlhelp qthelp devhelp epub latex latexpdf text man changes linkcheck doctest

help:
	$(PYTHON) make.py help

clean:
	$(PYTHON) make.py clean

bootstrap:
	$(PYTHON) make.py bootstrap

buildout:
	$(PYTHON) make.py buildout

update:
	$(PYTHON) make.py update

html:
	$(PYTHON) make.py html

htmlgz:
	$(PYTHON) make.py htmlgz

dirhtml:
	$(PYTHON) make.py dirhtml

singlehtml:
	$(PYTHON) make.py singlehtml

pickle:
	$(PYTHON) make.py pickle

json:
	$(PYTHON) make.py json

htmlhelp:
	$(PYTHON) make.py htmlhelp

qthelp:
	$(PYTHON) make.py qhelp

devhelp:
	$(PYTHON) make.py devhelp

epub:
	$(PYTHON) make.py epub

latex:
	$(PYTHON) make.py latex

latexpdf:
	$(PYTHON) make.py latexpdf

text:
	$(PYTHON) make.py text

man:
	$(PYTHON) make.py man

changes:
	$(PYTHON) make.py changes

linkcheck:
	$(PYTHON) make.py linkcheck

doctest:
	$(PYTHON) make.py doctest

