# Makefile for Sphinx documentation
#

# You can set these variables from the command line.
PYTHON    = python

help:
	$(PYTHON) make.py help

bootstrap:
	$(PYTHON) make.py bootstrap

buildout:
	$(PYTHON) make.py buildout

update:
	$(PYTHON) make.py update
